version: '3.7'

services:
  grafana:
    container_name: 'prometheus-amazon-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.4.1}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/prometheus-amazon-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/prometheus-amazon-datasource
