name: E2E Tests
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    paths-ignore:
      - 'docs/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
          check-latest: true
          cache-dependency-path: |
            subdir/go.sum
            tools/go.sum
      # NOT TESTING THE BACKEND YET
      # - name: Test backend
      #   uses: magefile/mage-action@v2
      #   with:
      #     version: latest
      #     args: coverage
      - name: Build backend
        uses: magefile/mage-action@v2
        with:
          version: latest
          args: buildAll
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install -g yarn && yarn install --frozen-lockfile;
      - name: Build Frontend
        run: |
          yarn build;
      - name: Start the docker container for E2E
        run: |
          docker compose -f docker-compose-debug.yaml pull
          docker compose -f docker-compose-debug.yaml up -d
      - name: Wait for prometheus to start
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:9090/-/ready'
          responseCode: 200
          timeout: 20000
          interval: 500
      - name: Wait for grafana to start
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3099/'
          responseCode: 200
          timeout: 20000
          interval: 500
      - name: Wait for prometheus to be configured in grafana
        uses: nev7n/wait_for_response@v1
        with:
          url: 'http://localhost:3099/api/datasources/uid/prometheus-amazon/health'
          responseCode: 200
          timeout: 20000
          interval: 500
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run E2E tests
        run: yarn test:e2e
      - name: Run E2E report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Run E2E videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30
      - name: Stop the docker container
        if: always()
        run: docker-compose -f docker-compose-debug.yaml down