name: run-backend-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 9 1 * *'

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        version: [10, 12, 14]

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'

      - name: Build
        run: go build -v ./...

      - name: Run backend tests
        run: go test -v ./...
