name: run-backend-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.0'

      - name: Build
        run: go build -o dist -v ./...

      - name: Run backend tests
        run: go test -v ./...
